### PR TITLE
More info on how to run/debug LEDMatrix code on linux

### PR DESCRIPTION
**Pull request by marcmerlin**
This allows for faster development/debugging.

### CODE REVIEW

**Comment by Jorgen-VikingGod** [comment]
Hi @marcmerlin thx for add this description - have to try this out

**Comment by marcmerlin** [comment]
Thanks @Jorgen-VikingGod . If you are already running linux, it should be as simple as a git clone, and then go in https://github.com/marcmerlin/ArduinoOnPc-FastLED-GFX-LEDMatrix/tree/master/examples/GFX_Table_Mark_Estes
and type make. Ideally neomatrix_config.h will auto detect the backend and select SDL output for linux (the same file is used to select other backends like FastLED, SmartMatrix, or TFTs).
This should give you a very nice set of demos that use LEDMatrix functionality pretty extensively.
Let me know if you run into any issues, and will gladly help.

**Comment by marcmerlin** [comment]
@Jorgen-VikingGod  I figured you might enjoy this.
The same exact code line for line, running LEDSprites Pacman (code I took from the original LEDSprites but changed to be 2D instead of 1D), on 24x32 on ESP8266/FastLED and 384x192 (Raspberry Pi 4, rgbmatrix):

https://github.com/marcmerlin/FastLED_NeoMatrix_SmartMatrix_LEDMatrix_GFX_Demos/tree/master/LEDMatrix/LEDSprites-Pacman  
This code can run on FastLED Matrices, TFT screens, RGBPanels via SmartMatrix, linux/SDL, and even Raspberry Pi via ArduinoOnPC (https://github.com/marcmerlin/ArduinoOnPc-FastLED-GFX-LEDMatrix )
Demos:
* https://www.youtube.com/watch?v=Re2MymDAlKE (24x32)
* https://www.youtube.com/watch?v=Mo2-I2BZqQM (384x192)

**Comment by Jorgen-VikingGod** [comment]
@marcmerlin looks awesome! Great work Marc.
Hopefully I will find some spare time soon, to finish my 15x15 Pixel WordClock (with multiple layers, Tetris, Snake, ...) running in ESP32 and maybe in near future with Alexa integration :rofl:

**Comment by marcmerlin** [comment]
@Jorgen-VikingGod if you don't mind my asking, as you know I started with neopixel matrices too (went all the way up to 64x64 which a solid week to build and takes a nice 160 amps on full white), I've now become a pixel/resolution junkie and despite their downsides, been using RGBPanels due to how many more pixels they offer for a given form factor.
Have you considered using RGBPanels at all? With an ESP32 you can trivially run 64x64 (up to 64x128) and still use LEDMatrix and your exact same code.

**Comment by Jorgen-VikingGod** [comment]
@marcmerlin I know. Have some projects based on RGBPanels. But for the WordClock I need the bigger pixel pitch to use a readable word mask.
Or do you know any RGBPanels with bigger pixel pitch? My current project uses 50x50cm "panel" with 15x15 NeoPixels matrix.

Btw. the long life quality is also much better on RGBPanels - some of my old NeoPixel projects are broken, because of some burned pixels (have to replace them often)

**Comment by marcmerlin** [comment]
@Jorgen-VikingGod yeah, tell me about it, WS2812, never again. At least WS2813 has a backup data line to get around bad pixels.
My 4096 neopixel array that ran LEDMatrix/Table_Mark_Estes was damaged quite a bit by by my first burning man, I lost over 50 pixels to playa dust, it took me forever to half fix it, splicing pixels in, and even then more still broke :(
It's too bad, it was cool while it worked:
http://marc.merlins.org/perso/arduino/post_2018-07-30_Building-a-64x64-Neopixel-Neomatrix-_4096-pixels_-running-NeoMatrix-FastLED-IR.html

**Pull request merged**
